title: KhyPoe
author: Khyzer
email: 
description:

# social links
twitter_username:  # DO NOT include the @ character, or else the build will fail!
github_username:  Khyzer # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
